name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Release
      run: dotnet publish -c Release --output ./app --properties:Version=1.0.0 --runtime win-x64

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-release
        path: ./app
